el_t01/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('el_t01/', include('el_t01_app.urls')),
    path('', include('el_t01_app.urls')),
    path('', include('el_t0001_app.urls')),
    path('', include('el_t0002_app.urls')),
    path('', include('el_t0003_app.urls')),
    path('', include('el_t0004_app.urls'))
]

el_t01_app/models.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
import os
from django.db import models
from django.contrib.auth.models import User
from django.db.models import JSONField


class Type_payment(models.Model):
    id = models.AutoField(primary_key=True)
    order = models.IntegerField(default=0, verbose_name=u'Order')
    caption = models.CharField(max_length=100, default='')
    verbal = models.CharField(max_length=30, default='')
    enabled = models.BooleanField(default=True, verbose_name=u'Enabled')
    is_active = models.BooleanField(default=True, verbose_name=u'Active')
    subs_enabled = models.BooleanField(default=False, verbose_name=u'Enabled for subscription')
    max_win = models.IntegerField(default=0, verbose_name=u'Max win')
    foto_1 = models.ImageField(upload_to='ticket/payment/', default='', blank=True, null=True, verbose_name=u'Logo')
    description_01 = models.TextField(default='', blank=True)
    description_02 = models.TextField(default='', blank=True)

    popup = models.BooleanField(default=False, verbose_name=u'Popup')
    txt_warning = models.CharField(max_length=1000, default='', blank=True, verbose_name=u'Popup message')
    link_redirect = models.CharField(max_length=100, default='', blank=True, verbose_name=u'Link action')

    def __str__(self):
        return self.caption


class UserPayCard(models.Model):
    id = models.AutoField(primary_key=True)
    user_id = models.ForeignKey(User, null=False, blank=False, on_delete=models.CASCADE,
                                related_name="user_paycard",
                                verbose_name=u'User')
    dt_lastpay = models.DateTimeField(auto_now_add=False, null=True, blank=True, verbose_name=u'Date last')
    tranzila_tk = models.CharField(max_length=100, null=False, blank=False)
    ccno = models.CharField(max_length=10, default='', blank=True)
    mask_card  = models.CharField(max_length=20, default='', blank=True)
    myid = models.CharField(max_length=20, default='', blank=True)
    expmonth = models.CharField(max_length=2, default='', blank=True)
    expyear = models.CharField(max_length=4, default='', blank=True)
    description = models.CharField(max_length=250, null=True, blank='True', verbose_name='Description')


class SubsManager(models.Model):
    id = models.AutoField(primary_key=True)
    enabled = models.BooleanField(default=True, verbose_name='Enabled')
    name = models.CharField(max_length=150, verbose_name='Name')
    description = models.TextField(default='', blank=True, verbose_name='Description')

    def __str__(self):
        return self.name


dict_subscription_creator = (
    ('00', 'Manager'),
    ('01', 'User')
)


class Subscription(models.Model):
    id = models.AutoField(primary_key=True)
    user_id = models.ForeignKey(User, null=False, blank=False, on_delete=models.CASCADE,
                                related_name="subs_user",
                                verbose_name=u'User subs')
    user_id_creator = models.ForeignKey(User, null=False, blank=False, on_delete=models.CASCADE,
                                        related_name="subs_user_creator",
                                        verbose_name=u'User subs creator')
    u_paycard = models.ForeignKey(UserPayCard, null=True, blank=True, on_delete=models.SET_NULL,
                                  related_name="subs_paycard", verbose_name=u'Pay Card')

    creator = models.CharField(max_length=2, default='00', blank=True, null=True, choices=dict_subscription_creator,
                               verbose_name='Creator')
    dt_add = models.DateTimeField(auto_now_add=False, null=False, blank=False, verbose_name=u'Date ADD')
    dt_modified = models.DateTimeField(auto_now_add=False, null=True, blank=True, verbose_name=u'Date modified')
    dt_start = models.DateTimeField(auto_now_add=False, null=False, blank=False, verbose_name=u'Date START')
    dt_stop = models.DateTimeField(auto_now_add=False, null=False, blank=False, verbose_name=u'Date STOP')
    enabled = models.BooleanField(default=True, verbose_name=u'Enabled')

    ticket_list = JSONField(default=dict, null=True, blank=True, verbose_name=u'Ticket List')
    day_1 = models.BooleanField(default=False, verbose_name=u'San')
    day_2 = models.BooleanField(default=False, verbose_name=u'Mon')
    day_3 = models.BooleanField(default=False, verbose_name=u'Tue')
    day_4 = models.BooleanField(default=False, verbose_name=u'Wed')
    day_5 = models.BooleanField(default=False, verbose_name=u'Thu')
    day_6 = models.BooleanField(default=False, verbose_name=u'Fri')
    day_7 = models.BooleanField(default=False, verbose_name=u'Sat')

    time_1 = models.CharField(max_length=5, default='00.00', verbose_name=u'Time San')
    time_2 = models.CharField(max_length=5, default='00.00', verbose_name=u'Time Mon')
    time_3 = models.CharField(max_length=5, default='00.00', verbose_name=u'Time Tue')
    time_4 = models.CharField(max_length=5, default='00.00', verbose_name=u'Time Wed')
    time_5 = models.CharField(max_length=5, default='00.00', verbose_name=u'Time Thu')
    time_6 = models.CharField(max_length=5, default='00.00', verbose_name=u'Time Fri')
    time_7 = models.CharField(max_length=5, default='00.00', verbose_name=u'Time Sat')

    amount_subs = models.DecimalField(max_digits=15, decimal_places=2, default=0, verbose_name=u'Amount_subs')
    amount_add = models.DecimalField(max_digits=15, decimal_places=2, default=0, verbose_name=u'Amount_add')
    amount_total = models.DecimalField(max_digits=15, decimal_places=2, default=0, verbose_name=u'Amount_total')

    paid_amount = models.DecimalField(max_digits=15, decimal_places=2, default=0, verbose_name=u'Paid amount')
    paid_date = models.DateTimeField(auto_now_add=False, null=True, blank=True, verbose_name=u'Paid Date')
    auto_pay = models.BooleanField(default=False, verbose_name=u'Auto Payment')
    last_pay = models.BooleanField(default=True, verbose_name=u'Last Pay OK')
    auto_pay_amount = models.DecimalField(max_digits=15, decimal_places=2, default=0, verbose_name=u'Auto Pay Amount')
    auto_pay_day = models.IntegerField(default=0, verbose_name=u'Auto Pay Day')

    total_tickets_amount = models.IntegerField(default=0, verbose_name=u'Total tickets amount')
    total_days_amount = models.IntegerField(default=0, verbose_name=u'Total days amount')
    description = models.TextField(default='', blank=True)

    manager = models.ForeignKey(SubsManager, null=True, blank=True, on_delete=models.PROTECT,
                                related_name="subs_manager", verbose_name=u'Manager')
    type_payment = models.ForeignKey(Type_payment, null=True, blank=True, on_delete=models.PROTECT,
                                     related_name="subs_type_payment", verbose_name=u'Payment type')
    bonus = models.FloatField(default=0, null=True, blank=True, verbose_name=u'Bonus')
    history = models.TextField(default='', null=True, blank=True)

    def __str__(self):
        return f"{self.id}-{self.user_id.email}"


class Task_subs_status(models.Model):
    id = models.AutoField(primary_key=True)
    order = models.IntegerField(default=0, verbose_name=u'Order')
    enabled = models.BooleanField(default=True, verbose_name=u'Enabled')
    caption = models.CharField(max_length=100, default='')
    verbal = models.CharField(max_length=30, default='')
    description = models.TextField(default='', blank=True)

    def __str__(self):
        return self.caption


class Task_subs(models.Model):
    id = models.AutoField(primary_key=True)
    t_status = models.ForeignKey(Task_subs_status, on_delete=models.PROTECT,
                                 related_name="t_task_subs_status", verbose_name=u'Status')
    dt_start = models.DateTimeField(auto_now_add=False, null=True, blank=True, verbose_name=u'Date START')
    dt_stop = models.DateTimeField(auto_now_add=False, null=True, blank=True, verbose_name=u'Date STOP')
    task_ok = models.TextField(default='', blank=True, verbose_name=u'Subs OK')
    task_error = models.TextField(default='', blank=True, verbose_name=u'Subs ERROR')
    task_ok_num = models.IntegerField(default=0, verbose_name=u'Count OK')
    task_error_num = models.IntegerField(default=0, verbose_name=u'Count ERROR')


class Type_balanceoperation(models.Model):
    id = models.AutoField(primary_key=True)
    order = models.IntegerField(default=0, verbose_name=u'Order')
    caption = models.CharField(max_length=100, default='')
    verbal = models.CharField(max_length=30, default='')
    verbal_payment = models.CharField(max_length=30, default='', blank=True)
    enabled = models.BooleanField(default=True, verbose_name=u'Enabled')
    max_win = models.IntegerField(default=0, verbose_name=u'Max win')
    for_balance = models.CharField(max_length=30, blank=True, default='') ## minus plus

    def __str__(self):
        return self.caption


class Type_balanceoperation_status(models.Model):
    id = models.AutoField(primary_key=True)
    order = models.IntegerField(default=0, verbose_name=u'Order')
    caption = models.CharField(max_length=100, default='', verbose_name=u'Caption')
    verbal = models.CharField(max_length=30, default='', verbose_name=u'Varbal')
    enabled = models.BooleanField(default=True, verbose_name=u'Enabled')

    def __str__(self):
        return self.caption


class Type_game_status(models.Model):
    id = models.AutoField(primary_key=True)
    order = models.IntegerField(default=0, verbose_name=u'Order')
    caption = models.CharField(max_length=100, default='', verbose_name=u'Caption')
    verbal = models.CharField(max_length=30, default='', verbose_name=u'Varbal')
    enabled = models.BooleanField(default=True, verbose_name=u'Enabled')

    def __str__(self):
        return self.caption


class Type_currency(models.Model):
    id = models.AutoField(primary_key=True)
    order = models.IntegerField(default=0, blank=True, null=True, verbose_name=u'Очередность')
    code = models.CharField(max_length=10, default='')

templates/common/cab_boss/_m_cabb_blank.html
{% load i18n %}
<div class="modal fade js-modal__cabb_blank" id="modal-lg">
    <div class="modal-dialog modal-lg js_ResAjax">
    </div>
</div>

templates/common/cab_boss/_m_cabb_payadd.html
{% load i18n %}
<div class="modal fade js-modal__cabb_payadd" id="modal-lg">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title text-secondary">{% trans 'Check Bank Transfer' %}</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-12" id="id_ResPayAdd">
                    </div>
                </div>
                <!-- /.row -->
            </div>
            <div class="modal-footer justify-content-between">
                <button type="button"
                        class="btn btn-dark"
                        data-dismiss="modal"
                        onclick="btn_payadd_conf('01')"
                >{% trans 'Confirm' %}</button>
                <button type="button"
                        class="btn btn-dark"
                        data-dismiss="modal"
                        onclick="btn_payadd_conf('02')"
                >{% trans 'Block' %}</button>
                <button type="button"
                        class="btn btn-dark"
                        data-dismiss="modal"
                >{% trans 'Close' %}</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal -->

templates/common/cab_boss/_templ_blacklist_new.html
{% load static %}
{% load i18n %}

<div class="modal-body">
    <div class="row">
        <div class="col-12">
            <section class="main-bg">
                <div class="container cabs_newtask-box">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="card card-secondary cab-table-border">
                                <div class="card-header">
                                    <h3 class="card-title">{% trans 'Create New BlackList' %}</h3>
                                </div>
                                <input id="id_user_id" name="f_t_user" type="hidden" value="{{ m_user.id }}">
                                <div class="card-body">
                                    <div class="row">
                                        <div class="col-sm-6">
                                            <div class="form-group">
                                                <label for="id_t_type">{% trans 'Type blacklist' %}</label>
                                                <select class="custom-select"
                                                        id="id_t_type"
                                                        name="f_t_type">
                                                    {% for Item in dict_blacklist_type %}
                                                        <option value="{% trans Item.verbal %}">{% trans Item.caption %}</option>
                                                    {% endfor %}
                                                </select>
                                            </div>
                                        </div>
                                        <div class="col-sm-6">
                                            <div class="form-group">
                                                <label for="id_t_text">{% trans 'Text' %}</label>
                                                <input type="text"
                                                       id="id_t_text"
                                                       class="form-control"
                                                       name="f_t_text"
                                                       value=""
                                                >
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-sm-12">
                                            <div class="form-group">
                                                <label for="id_t_description">{% trans "Description" %}</label>
                                                <textarea class="form-control" rows="3"
                                                          id="id_t_description"
                                                          name="f_t_description"
                                                          placeholder={% trans "Description" %}></textarea>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- /.card-body -->
                                <div class="row flex-md-row ">
                                    <div class="col-md-12 d-flex justify-content-center">
                                        <div class="modal-footer justify-content-between">
                                            <button type="button"
                                                    class="btn btn-dark"
                                                    {#                                                    data-dismiss="modal"#}
                                                    onclick="btn_blocklist_save()"
                                            >{% trans 'Save' %}</button>
                                            <button type="button"
                                                    class="btn btn-dark"
                                                    data-dismiss="modal"
                                            >{% trans 'Close' %}</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- /.card -->
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
    <!-- /.row -->
</div>

<script type="text/javascript">
    function btn_blocklist_save() {

        let m_t_type = $("#id_t_type").val();
        let m_t_text = $("#id_t_text").val();
        let m_t_description = $("#id_t_description").val();
        console.log("m_t_type        = ", m_t_type);
        console.log("m_t_text        = ", m_t_text);
        console.log("m_t_description = ", m_t_description);

        $.ajax({
            type: "POST",
            async: false,
            data: {
                csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
                t_type: m_t_type,
                t_text: m_t_text,
                t_description: m_t_description,
            },
            url: "/cabb_blocklist_save/",
            success: function (res) {
                if (res.AnswerCod == '01') {
                    $('.js-modal__cabb_form').modal('hide');
                    location.reload();
                } else {
                    Swal.fire({
                        icon: 'error',
                        title: gettext('ERROR'),
                        background: '#cacaca',
                        html: res.AnswerText,
                        confirmButtonText: gettext('Back to form'),
                        confirmButtonColor: '#dd3333',
                    });
                    return false;
                }
            },
            error: function (res) {
                Swal.fire({
                    icon: 'error',
                    title: gettext('ERROR'),
                    background: '#cacaca',
                    html: gettext("An error occured, please try again later."),
                    confirmButtonText: gettext('Back to form'),
                    confirmButtonColor: '#dd3333',
                });
                return false;
            }
        });
    }
</script>

templates/common/cab_boss/cabb_cabala.html
{% load static %}
{% load i18n %}
{#<!-- lottery video Area Start -->#}
{#<section class="cabb-page">#}
{#    <div class="container">#}
{#        <div class="row justify-content-center">#}
{#            <div class="col-lg-12">#}
{#                <div class="game-item-box">#}
{#                    <div class="row justify-content-center">#}
{#                        <div class="col-lg-12 col-md-12">#}
{#                            <div class="section-heading">#}
{#                                <h5 class="subtitle">11-11-22{{ item_ticket_type.caption }}</h5>#}
{#                            </div>#}
{#                        </div>#}
{#                    </div>#}
{#                    <div class="row">#}
{#                        <div class="col-lg-12">#}
{#                            <div class="card">#}
{##}
{#                            </div>#}
{#                        </div>#}
{#                    </div>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
{#    </div>#}
{#</section>#}
<!-- lottery video Area End -->
{% load static %}
{% load i18n %}
<section class="cabb-page">
    <div class="container_cabb">
        <div class="justify-content-center">
            {#            <div class="col-lg-12">#}
            <div class="card">
            <div class="card-header">
                <h5 class="card-title m-0">{% trans 'List Games' %}</h5>
            </div>
            {% if l_find %}
            {% include l_find %}
            {% endif %}
            <div class="card-body">
                <div class="dataTables_wrapper dt-bootstrap4">
                {% if False %}
                    <div class="row">
                        <div class="col-sm-12 col-md-6">
                            <div class="dataTables_length" id="example1_length"><label>Show <select
                                    name="example1_length"
                                    aria-controls="example1"
                                    class="custom-select custom-select-sm form-control form-control-sm">
                                <option value="10">10</option>
                                <option value="25">25</option>
                                <option value="50">50</option>
                                <option value="100">100</option>
                            </select> entries</label></div>
                        </div>
                        {#            <div class="col-sm-12 col-md-6">#}
                        {#                <div id="example1_filter" class="dataTables_filter"><label>Search:<input type="search"#}
                        {#                                                                                         class="form-control form-control-sm"#}
                        {#                                                                                         placeholder=""#}
                        {#                                                                                         aria-controls="example1"></label>#}
                        {#                </div>#}
                        {#            </div>#}
                    </div>
                {% endif %}
                    <div class="row">
                        <div class="col-sm-12 table-cabb">

                            <table id="id_table_tic" class="table table-bordered table-striped ">
                                <thead>
                                <tr>
                                    <th></th>
                                    <th>{% trans '#' %}</th>
                                    <th>{% trans 'Create' %}</th>
                                    <th>{% trans 'Status' %}</th>
                                    <th>{% trans 'User login' %}</th>
                                    <th>{% trans 'User name' %}</th>
                                    <th>{% trans 'User phone' %}</th>
                                    <th>{% trans 'Payment Methody' %}</th>
                                    <th>{% trans 'Sum' %}</th>
                                    <th>{% trans 'Tickets' %}</th>
                                    <th>{% trans 'Date start' %}</th>
                                    <th>{% trans 'Date stop' %}</th>
                                    <th>{% trans 'IP' %}</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for ItemGame in list_games %}
                                    <tr class="js_tic_row">
                                        <td>
                                            <button type="button"
                                                    class="btn btn-info mybtn_cabb1"
                                                    onclick="btn_ticket_result({{ ItemGame.id }})">
                                                {% trans 'Edit' %}
                                            </button>
{#                                            <br>#}
                                            {% if True %}
                                            <button type="button"
                                                    class="btn btn-info mybtn_cabb1"
                                                    onclick="btn_ticket_edit({{ ItemGame.id }})">
                                                {% trans 'Show tickets' %}
                                            </button>
{#                                            <br>#}
                                            {% endif %}
                                            {% if True %}
                                                <button type="button"
                                                        class="btn btn-info mybtn_cabb1"
                                                        onclick="btn_ticket_result({{ ItemGame.id }})">
                                                    {% trans 'Show Pay' %}
                                                </button>
                                            {% endif %}
                                        </td>
                                        <td>{{ ItemGame.id }}</td>
                                        <td>{{ ItemGame.dt_add|date:"d.m.Y H:i:s" }}</td>
                                        <td>
                                            {{ ItemGame.t_status.caption }}
                                        </td>
                                        <td>{{ ItemGame.user_id }}</td>
                                        <td>{{ ItemGame.user_id.profile.name }}</td>
                                        <td>
                                            <a href="https://wa.me/+972{{ ItemGame.user_id.profile.mobile }}"
                                               target="_blank"
                                               style="text-decoration:none;"
                                               role="link"
                                               aria-label="link to whatsapp">
                                               <img src="{% static 'img/whatsapp.png' %}"
                                                    height="25"
                                                    alt="link to whatsapp">
                                            </a>
                                            {{ ItemGame.user_id.profile.mobile }}
                                        </td>
                                        <td>{{ ItemGame.t_payment }}</td>
                                        <td>{{ ItemGame.ticket_sum }}</td>
                                        <td>
{#                                            {{ ItemGame.ticket_list }}#}
                                            {% for ItemOrderTic in ItemGame.ticket_list.list_order %}
                                                {{ ItemOrderTic.tic_caption }} ( {{ ItemOrderTic.tic_num }} )<br>
                                            {% endfor %}
                                        </td>
                                        <td>{{ ItemGame.dt_start|date:"d.m.Y H:i:s" }}</td>
                                        <td>{{ ItemGame.dt_stop|date:"d.m.Y H:i:s" }}</td>
                                        <td>{{ ItemGame.user_ip }}</td>

                                    </tr>
                                {% endfor %}
                                </tbody>
                                <tfoot>
                                <tr>
                                    <th></th>
                                    <th>{% trans '#' %}</th>
                                    <th>{% trans 'Create' %}</th>
                                    <th>{% trans 'Status' %}</th>
                                    <th>{% trans 'User login' %}</th>
                                    <th>{% trans 'User name' %}</th>
                                    <th>{% trans 'User phone' %}</th>
                                    <th>{% trans 'Payment Methody' %}</th>
                                    <th>{% trans 'Sum' %}</th>
                                    <th>{% trans 'Tickets' %}</th>
                                    <th>{% trans 'Date start' %}</th>
                                    <th>{% trans 'Date stop' %}</th>
                                    <th>{% trans 'IP' %}</th>
                                </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                        {% include 'common/_pagination.html' %}
                </div>
            </div>
            </div>
            <!-- /.card-body -->
        </div>
    </div>
</section>

templates/common/cab_boss/layout.html
{% load static %}
<!DOCTYPE html>
<html {% if lang == "he" or lang == "ar" %}dir="rtl"{% endif %}>
{#<html>#}
<head>
    <title>{{ PAGE_TITLE }}</title>
    {% for item_head in l_head_list %}
        {% include item_head %}
    {% endfor %}
</head>

<body>
{% csrf_token %}
<!-- preloader area start -->
<div class="preloader" id="preloader">
    <div class="loader loader-1">
        <div class="loader-outter"></div>
        <div class="loader-inner"></div>
    </div>
</div>
<!-- preloader area end -->

{% for item_header in l_header_list %}
    {% include item_header %}
{% endfor %}

{% block layoutbody %}
{% endblock %}

{% for item_footer in l_footer_list %}
    {% include item_footer %}
{% endfor %}

<!-- Back to Top Start -->
<div class="bottomtotop">
    <i class="fas fa-chevron-right"></i>
</div>
<!-- Back to Top End -->

{% for item_script in l_script_list %}
    {% include item_script %}
{% endfor %}

{% for item_modal in l_modal_list %}
    {% include item_modal %}
{% endfor %}

</body>
</html>