el_t01/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('el_t01/', include('el_t01_app.urls')),
    path('', include('el_t01_app.urls')),
    path('', include('el_t0001_app.urls')),
    path('', include('el_t0002_app.urls')),
    path('', include('el_t0003_app.urls')),
    path('', include('el_t0004_app.urls'))
]

el_t01_app/models.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
import os
from django.db import models
from django.contrib.auth.models import User
from django.db.models import JSONField


class Type_payment(models.Model):
    id = models.AutoField(primary_key=True)
    order = models.IntegerField(default=0, verbose_name=u'Order')
    caption = models.CharField(max_length=100, default='')
    verbal = models.CharField(max_length=30, default='')
    enabled = models.BooleanField(default=True, verbose_name=u'Enabled')
    is_active = models.BooleanField(default=True, verbose_name=u'Active')
    subs_enabled = models.BooleanField(default=False, verbose_name=u'Enabled for subscription')
    max_win = models.IntegerField(default=0, verbose_name=u'Max win')
    foto_1 = models.ImageField(upload_to='ticket/payment/', default='', blank=True, null=True, verbose_name=u'Logo')
    description_01 = models.TextField(default='', blank=True)
    description_02 = models.TextField(default='', blank=True)

    popup = models.BooleanField(default=False, verbose_name=u'Popup')
    txt_warning = models.CharField(max_length=1000, default='', blank=True, verbose_name=u'Popup message')
    link_redirect = models.CharField(max_length=100, default='', blank=True, verbose_name=u'Link action')

    def __str__(self):
        return self.caption


class UserPayCard(models.Model):
    id = models.AutoField(primary_key=True)
    user_id = models.ForeignKey(User, null=False, blank=False, on_delete=models.CASCADE,
                                related_name="user_paycard",
                                verbose_name=u'User')
    dt_lastpay = models.DateTimeField(auto_now_add=False, null=True, blank=True, verbose_name=u'Date last')
    tranzila_tk = models.CharField(max_length=100, null=False, blank=False)
    ccno = models.CharField(max_length=10, default='', blank=True)
    mask_card  = models.CharField(max_length=20, default='', blank=True)
    myid = models.CharField(max_length=20, default='', blank=True)
    expmonth = models.CharField(max_length=2, default='', blank=True)
    expyear = models.CharField(max_length=4, default='', blank=True)
    description = models.CharField(max_length=250, null=True, blank='True', verbose_name='Description')


class SubsManager(models.Model):
    id = models.AutoField(primary_key=True)
    enabled = models.BooleanField(default=True, verbose_name='Enabled')
    name = models.CharField(max_length=150, verbose_name='Name')
    description = models.TextField(default='', blank=True, verbose_name='Description')

    def __str__(self):
        return self.name


dict_subscription_creator = (
    ('00', 'Manager'),
    ('01', 'User')
)


class Subscription(models.Model):
    id = models.AutoField(primary_key=True)
    user_id = models.ForeignKey(User, null=False, blank=False, on_delete=models.CASCADE,
                                related_name="subs_user",
                                verbose_name=u'User subs')
    user_id_creator = models.ForeignKey(User, null=False, blank=False, on_delete=models.CASCADE,
                                        related_name="subs_user_creator",
                                        verbose_name=u'User subs creator')
    u_paycard = models.ForeignKey(UserPayCard, null=True, blank=True, on_delete=models.SET_NULL,
                                  related_name="subs_paycard", verbose_name=u'Pay Card')

    creator = models.CharField(max_length=2, default='00', blank=True, null=True, choices=dict_subscription_creator,
                               verbose_name='Creator')
    dt_add = models.DateTimeField(auto_now_add=False, null=False, blank=False, verbose_name=u'Date ADD')
    dt_modified = models.DateTimeField(auto_now_add=False, null=True, blank=True, verbose_name=u'Date modified')
    dt_start = models.DateTimeField(auto_now_add=False, null=False, blank=False, verbose_name=u'Date START')
    dt_stop = models.DateTimeField(auto_now_add=False, null=False, blank=False, verbose_name=u'Date STOP')
    enabled = models.BooleanField(default=True, verbose_name=u'Enabled')

    ticket_list = JSONField(default=dict, null=True, blank=True, verbose_name=u'Ticket List')
    day_1 = models.BooleanField(default=False, verbose_name=u'San')
    day_2 = models.BooleanField(default=False, verbose_name=u'Mon')
    day_3 = models.BooleanField(default=False, verbose_name=u'Tue')
    day_4 = models.BooleanField(default=False, verbose_name=u'Wed')
    day_5 = models.BooleanField(default=False, verbose_name=u'Thu')
    day_6 = models.BooleanField(default=False, verbose_name=u'Fri')
    day_7 = models.BooleanField(default=False, verbose_name=u'Sat')

    time_1 = models.CharField(max_length=5, default='00.00', verbose_name=u'Time San')
    time_2 = models.CharField(max_length=5, default='00.00', verbose_name=u'Time Mon')
    time_3 = models.CharField(max_length=5, default='00.00', verbose_name=u'Time Tue')
    time_4 = models.CharField(max_length=5, default='00.00', verbose_name=u'Time Wed')
    time_5 = models.CharField(max_length=5, default='00.00', verbose_name=u'Time Thu')
    time_6 = models.CharField(max_length=5, default='00.00', verbose_name=u'Time Fri')
    time_7 = models.CharField(max_length=5, default='00.00', verbose_name=u'Time Sat')

    amount_subs = models.DecimalField(max_digits=15, decimal_places=2, default=0, verbose_name=u'Amount_subs')
    amount_add = models.DecimalField(max_digits=15, decimal_places=2, default=0, verbose_name=u'Amount_add')
    amount_total = models.DecimalField(max_digits=15, decimal_places=2, default=0, verbose_name=u'Amount_total')

    paid_amount = models.DecimalField(max_digits=15, decimal_places=2, default=0, verbose_name=u'Paid amount')
    paid_date = models.DateTimeField(auto_now_add=False, null=True, blank=True, verbose_name=u'Paid Date')
    auto_pay = models.BooleanField(default=False, verbose_name=u'Auto Payment')
    last_pay = models.BooleanField(default=True, verbose_name=u'Last Pay OK')
    auto_pay_amount = models.DecimalField(max_digits=15, decimal_places=2, default=0, verbose_name=u'Auto Pay Amount')
    auto_pay_day = models.IntegerField(default=0, verbose_name=u'Auto Pay Day')

    total_tickets_amount = models.IntegerField(default=0, verbose_name=u'Total tickets amount')
    total_days_amount = models.IntegerField(default=0, verbose_name=u'Total days amount')
    description = models.TextField(default='', blank=True)

    manager = models.ForeignKey(SubsManager, null=True, blank=True, on_delete=models.PROTECT,
                                related_name="subs_manager", verbose_name=u'Manager')
    type_payment = models.ForeignKey(Type_payment, null=True, blank=True, on_delete=models.PROTECT,
                                     related_name="subs_type_payment", verbose_name=u'Payment type')
    bonus = models.FloatField(default=0, null=True, blank=True, verbose_name=u'Bonus')
    history = models.TextField(default='', null=True, blank=True)

    def __str__(self):
        return f"{self.id}-{self.user_id.email}"


class Task_subs_status(models.Model):
    id = models.AutoField(primary_key=True)
    order = models.IntegerField(default=0, verbose_name=u'Order')
    enabled = models.BooleanField(default=True, verbose_name=u'Enabled')
    caption = models.CharField(max_length=100, default='')
    verbal = models.CharField(max_length=30, default='')
    description = models.TextField(default='', blank=True)

    def __str__(self):
        return self.caption


class Task_subs(models.Model):
    id = models.AutoField(primary_key=True)
    t_status = models.ForeignKey(Task_subs_status, on_delete=models.PROTECT,
                                 related_name="t_task_subs_status", verbose_name=u'Status')
    dt_start = models.DateTimeField(auto_now_add=False, null=True, blank=True, verbose_name=u'Date START')
    dt_stop = models.DateTimeField(auto_now_add=False, null=True, blank=True, verbose_name=u'Date STOP')
    task_ok = models.TextField(default='', blank=True, verbose_name=u'Subs OK')
    task_error = models.TextField(default='', blank=True, verbose_name=u'Subs ERROR')
    task_ok_num = models.IntegerField(default=0, verbose_name=u'Count OK')
    task_error_num = models.IntegerField(default=0, verbose_name=u'Count ERROR')


class Type_balanceoperation(models.Model):
    id = models.AutoField(primary_key=True)
    order = models.IntegerField(default=0, verbose_name=u'Order')
    caption = models.CharField(max_length=100, default='')
    verbal = models.CharField(max_length=30, default='')
    verbal_payment = models.CharField(max_length=30, default='', blank=True)
    enabled = models.BooleanField(default=True, verbose_name=u'Enabled')
    max_win = models.IntegerField(default=0, verbose_name=u'Max win')
    for_balance = models.CharField(max_length=30, blank=True, default='') ## minus plus

    def __str__(self):
        return self.caption


class Type_balanceoperation_status(models.Model):
    id = models.AutoField(primary_key=True)
    order = models.IntegerField(default=0, verbose_name=u'Order')
    caption = models.CharField(max_length=100, default='', verbose_name=u'Caption')
    verbal = models.CharField(max_length=30, default='', verbose_name=u'Varbal')
    enabled = models.BooleanField(default=True, verbose_name=u'Enabled')

    def __str__(self):
        return self.caption


class Type_game_status(models.Model):
    id = models.AutoField(primary_key=True)
    order = models.IntegerField(default=0, verbose_name=u'Order')
    caption = models.CharField(max_length=100, default='', verbose_name=u'Caption')
    verbal = models.CharField(max_length=30, default='', verbose_name=u'Varbal')
    enabled = models.BooleanField(default=True, verbose_name=u'Enabled')

    def __str__(self):
        return self.caption


class Type_currency(models.Model):
    id = models.AutoField(primary_key=True)
    order = models.IntegerField(default=0, blank=True, null=True, verbose_name=u'Очередность')
    code = models.CharField(max_length=10, default='')

templates/common/cab_boss_subs/_cab_find_subs.html
{% load static %}
{% load i18n %}
<div class="card card-default collapsed-card">
    <div class="card-header">
        <h3 class="card-title">{% trans 'Search' %}</h3>
        <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse">
                <i class="fas fa-plus"></i>
            </button>
        </div>
    </div>
    <div class="card-body" style="display: none;">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label>{% trans 'Date range create:' %}</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                        <span class="input-group-text">
                          <i class="far fa-calendar-alt"></i>
                        </span>
                        </div>
                        <input type="text"
                               class="form-control float-right"
                               id="id_find_date_range_empty"
                               name="find_date_range"
                               value="{{ date_range }}"
                        >
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label>{% trans 'Date range subscription period:' %}</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                      <span class="input-group-text">
                        <i class="far fa-calendar-alt"></i>
                      </span>
                        </div>
                        <input type="text"
                               class="form-control float-right"
                               id="id_find_date_range_2_empty"
                               name="find_date_range_2"
                               value="{{ date_range_2 }}"
                        >
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label>{% trans 'Email owner:' %}</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text">
                                <i class="fas fa-edit"></i>
                            </span>
                        </div>
                        <input type="text"
                               class="form-control float-right"
                               id="id_find_uemail"
                               name="find_uemail"
                               value="{{ m_uEmail }}"
                        >
                    </div>
                </div>
            </div>
            <div class="col-md-2">
                <div class="form-group">
                    <label>{% trans 'Only active' %}</label>
                    <div class="input-group">
                        <input type="checkbox"
                               class="form-control float-right"
                               id="id_find_active"
                               name="find_active"
                               value="1"
                               {% if m_active %} checked {% endif %}
                        >
                    </div>
                </div>
            </div>
            <div class="col-sm-12">
                <label class="mr-3">{% trans 'Week days:' %}</label>
                <div id="id_weekdays" class="form-check form-check-inline">

                    <input id="id_day_1" class="form-check-input" type="checkbox"
                           {% if '1' in weekdays %} checked {% endif %}>
                    <label class="form-check-label mr-3" for="id_day_1">{% trans 'Sunday' %}</label>

                    <input id="id_day_2" class="form-check-input" type="checkbox"
                           {% if '2' in weekdays %} checked {% endif %}>
                    <label class="form-check-label mr-3" for="id_day_2">{% trans 'Monday' %}</label>

                    <input id="id_day_3" class="form-check-input" type="checkbox"
                           {% if '3' in weekdays %} checked {% endif %}>
                    <label class="form-check-label mr-3" for="id_day_3">{% trans 'Tuesday' %}</label>

                    <input id="id_day_4" class="form-check-input" type="checkbox"
                           {% if '4' in weekdays %} checked {% endif %}>
                    <label class="form-check-label mr-3" for="id_day_4">{% trans 'Wednesday' %}</label>

                    <input id="id_day_5" class="form-check-input" type="checkbox"
                           {% if '5' in weekdays %} checked {% endif %}>
                    <label class="form-check-label mr-3" for="id_day_5">{% trans 'Thursday' %}</label>

                    <input id="id_day_6" class="form-check-input" type="checkbox"
                           {% if '6' in weekdays %} checked {% endif %}>
                    <label class="form-check-label mr-3" for="id_day_6">{% trans 'Friday' %}</label>

                    <input id="id_day_7" class="form-check-input" type="checkbox"
                           {% if '7' in weekdays %} checked {% endif %}>
                    <label class="form-check-label mr-3" for="id_day_7">{% trans 'Saturday' %}</label>
                </div>
            </div>

            <div class="card-tools">
                <div class="input-group input-group-sm">
                    <button type="button"
                            onclick="btn_form_find()"
                            class="btn btn-info "
                    ><i class="fas fa-search"></i>{% trans 'Show' %}
                    </button>
                </div>
            </div>

        </div>
    </div>
</div>

templates/common/cab_boss_subs/subs_bonus_form.html
{% load static %}
{% load i18n %}
<div class="modal-body">
    <div class="row">
        <div class="col-12">
            <section class="main-bg">
                <div class="container cabs_newtask-box">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="card card-secondary cab-table-border">
                                <div class="card-header">
                                    <h3 class="card-title">{{ m_form_title }}</h3>
                                </div>
                                <div class="card-body">
                                    <div class="row">
                                        <div class="col-sm-4">
                                             <div class="form-group">
                                                 <div class="form-group clearfix">
                                                    <div class="icheck-success d-inline">
                                                        <input type="checkbox"
                                                               class="js__calc_check"
                                                        {% if m_form_type == 'new' %}
                                                        checked
                                                        {% else %}
                                                        {% if m_enabled %}
                                                        checked
                                                        {% endif %}
                                                        {% endif %}
                                                        id="id_enabled"
                                                        name="f_enabled"
                                                        value="m_enabled">
                                                        <label for="id_enabled">
                                                            {% trans 'Enabled' %}
                                                        </label>
                                                    </div>
                                                </div>

                                             </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-sm-6">
                                            <div class="form-group">
                                                <label for="id_ticket_type">{% trans 'Type ticket' %}</label>
                                                <select class="custom-select js__calc_select"
                                                        id="id_ticket_type"
                                                        name="f_ticket_type">
                                                    {% for Item in dict_tickets_type %}
                                                        <option
                                                                {% if Item.verbal == m_ticket_type.verbal %} selected="selected"
                                                                {% endif %}
                                                                data-cost="{{ Item.cost_2 }}"
                                                                value="{% trans Item.verbal %}">{% trans Item.caption %} ({{ Item.cost_2 }}) </option>
                                                    {% endfor %}
                                                </select>
                                            </div>
                                        </div>
                                        <div class="col-sm-2">
                                            <div class="form-group">
                                                <label for="id_min_days">{% trans 'Min days' %}</label>
                                                <input type="number"
                                                       id="id_min_days"
                                                       class="form-control"
                                                       name="f_min_days"
                                                       value="{{ m_min_days }}"
                                                       >
                                            </div>
                                        </div>
                                        <div class="col-sm-2">
                                            <div class="form-group">
                                                <label for="id_max_days">{% trans 'Max days' %}</label>
                                                <input type="number"
                                                       id="id_max_days"
                                                       class="form-control"
                                                       name="f_max_days"
                                                       value="{{ m_max_days }}"
                                                       >
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-sm-6">
                                         <div class="form-group">
                                            <label for="id_payment_type">{% trans 'Payment type' %}</label>
                                             <select class="form-control"
                                                     id="id_payment_type"
                                                     name="f_payment_type">
                                                 {% for payment_type in m_payment_types_list %}
                                                 <option {% if payment_type == m_type_payment %} selected="selected" {% endif %}
                                                         value="{{ payment_type.verbal }}">{{ payment_type.caption }}</option>
                                                    {% endfor %}
                                                 </select>
                                         </div>
                                    </div>
                                         <div class="col-sm-4">
                                            <div class="form-group">
                                                <label for="id_amount">{% trans 'Bonus amount' %}</label>
                                                <input type="number"
                                                       step="0.01"
                                                       id="id_amount"
                                                       class="form-control"
                                                       name="f_amount"
                                                       value="{{ m_bonus_amount }}"
                                                       >
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-sm-6">
                                         <div class="form-group">
                                            <label for="id_manager">{% trans 'Manager' %}</label>
                                             <select class="form-control"
                                                     id="id_manager"
                                                     name="f_manager">
                                                 <option value="all_managers" {% if m_for_all %} selected="selected" {% endif %}
                                                 >{% trans 'For all managers' %}</option>
                                                 {% for manager in m_managers_list %}
                                                 <option {% if manager == m_manager %} selected="selected" {% endif %}
                                                         value="{{ manager.id }}">{{ manager.name }}
                                                 </option>
                                                 {% endfor %}
                                             </select>
                                         </div>
                                    </div>
                                </div>
                            </div>

                            <div class="row flex-md-row ">
                                <div class="col-md-12 d-flex justify-content-center">
                                    <div class="modal-footer justify-content-between">
                                        <button type="button"
                                                class="btn btn-dark"
                                                onclick="btn_subs_bonus_save()"
                                        >{% trans 'Save' %}</button>
                                        <button type="button"
                                                class="btn btn-dark"
                                                data-dismiss="modal"
                                        >{% trans 'Close' %}</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
</div>
<script type="text/javascript">
    function btn_subs_bonus_save() {
        let enabled = 0;
        if ($('#id_enabled').is(':checked')) { enabled = 1}
        let manager = $("#id_manager").val(),
            payment_type = $("#id_payment_type").val(),
            ticket_type = $("#id_ticket_type").val(),
            min_days = +$("#id_min_days").val(),
            max_days = +$("#id_max_days").val(),
            bonus_amount = $("#id_amount").val();
        $.ajax({
                type: "POST",
                async: false,
                data: {
                    csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
                    m_form_type: '{{ m_form_type }}',
                    f_id: '{{ m_item_id }}',
                    f_enabled: enabled,
                    f_manager: manager,
                    f_payment_type: payment_type,
                    f_ticket_type: ticket_type,
                    f_min_days: min_days,
                    f_max_days: max_days,
                    f_bonus_amount: bonus_amount
                },
                url: "/subs_bonus_form_save/",
                success: function (res) {
                    if (res.AnswerCod == '01') {
                        $('.js-modal__cabb_form').modal('hide');
                        location.reload();
                    } else {
                        Swal.fire({
                            icon: 'error',
                            title: gettext('ERROR'),
                            background: '#cacaca',
                            html: res.AnswerText,
                            confirmButtonText: gettext('Back to form'),
                            confirmButtonColor: '#dd3333',
                        });
                        return false;
                    }
                },
                error: function (res) {
                    Swal.fire({
                        icon: 'error',
                        title: gettext('ERROR'),
                        background: '#cacaca',
                        html: gettext("An error occured, please try again later."),
                        confirmButtonText: gettext('Back to form'),
                        confirmButtonColor: '#dd3333',
                    });
                    return false;
                }
            });

    }
</script>